layout_spectrum: 0.5668455942068249
typography_spectrum: 0.10735409683547914
color:
  brandStrength: 0.5967786288820207
  lightness: 0.814995318185538
  saturation: 0.38307390245608985
  rhythmicContrast: 0.010563228745013475
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
name: Cham Diaspora Project
