typography_spectrum: 0.10735409683547914
color:
  brandStrength: 0.5967786288820207
  lightness: 0.814995318185538
  saturation: 0.38307390245608985
  rhythmicContrast: 0.010563228745013475
  brandColors:
    - '#F8F9FC'
    - '#224FAA'
    - '#A62626'
    - '#3D588F'
    - '#C7CAD1'
layout_spectrum: 0.5668455942068249
logo: null
name: Cham Diaspora Project
title: Cham Diaspora Project
